# Generated by Django 4.2.13 on 2024-06-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_rename_post_comment_comment_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time_in',
            new_name='comm_time_in',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
